version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    command: mongod --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: dimitri-admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cheatty
    ports:
      - 27017:27017
    volumes:
      - mongodb_server_data:/data/db
      - ./docker/mongo-entrypoint/entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js

  nginx:
    image: nginx
    depends_on:
      - "api"
      - "app"
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dimitri-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081

  api:
    build: docker/api
    depends_on:
      - "mongo"
    volumes:
      - ./api:/usr/src/project/api
    environment:
      PORT: '3002'
      ORIGIN: 'http://localhost:5000'
      SENTRY: 'https://c387f8457a0a406aa3b324c4203b41fe@o554441.ingest.sentry.io/5683174'
      TRACES: '1.0'
      TYPE: 'mongodb'
      HOST: 'mongo'
      DB_PORT: '27017'
      DATABASE: 'cheatty'
      USERNAME: 'dimitri-user'
      PASSWORD: 'example'

  app:
    build: docker/app
    volumes:
      - ./app:/usr/src/project/app
    depends_on:
      - "api"
    environment:
      PORT: '5000'
      API: "http://localhost:3002"
      SENTRYURL: "https://6cebdab6517647d5a3e34ab924160fab@o554441.ingest.sentry.io/5683154"
      SENTRYTRACES: 1.0

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8027:8025

volumes:
  mongodb_server_data:
