version: 2.1
jobs:
  app-build:
    working_directory: ~/cheatty/app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: PWD
          command: "pwd"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Validate
          command: npm run validate
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - app-build
