version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:15.3.0

commands:
  npm_install:
    parameters:
      cache_key:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}
            - npm-install-<< parameters.cache_key >>
          paths:
            - node_modules
      - run:
          command: npm install
      - save_cache:
          key: npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  app-npm-install:
    executor: node
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - npm_install:
          cache_key: app
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
  app-lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run linter
          command: cd app && npm run lint
  app-validate:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run validate
          command: cd app && npm run validate
  app-build:
    executor: node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: cd app && npm run build:prod
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/public
workflows:
  version: 2
  build:
    jobs:
      - app-npm-install
      - app-lint:
          requires:
            - app-npm-install
      - app-validate:
          requires:
            - app-npm-install
      - app-build:
          requires:
            - app-lint
            - app-validate
