version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:15.3.0

commands:
  npm_install:
    parameters:
      cache_key:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}
            - npm-install-<< parameters.cache_key >>
          paths:
            - node_modules
      - run:
          command: npm install
      - save_cache:
          key: npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  app-npm-install:
    executor: node
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - npm_install:
          cache_key: app
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
  api-npm-install:
    executor: node
    working_directory: ~/project/api
    steps:
      - checkout:
          path: ~/project
      - npm_install:
          cache_key: api
      - persist_to_workspace:
          root: ~/project
          paths:
            - api/node_modules
  app-lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run linter
          command: cd app && npm run lint
  api-lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run linter
          command: cd api && npm run lint
  app-validate:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run validate
          command: cd app && npm run validate
  app-build:
    executor: node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: cd app && npm run build:prod
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/public
  api-build:
    executor: node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: cd api && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - api/dist
  build-archives:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Remove dev dependencies from app
          command: cd app &&  npm install --only=production
      - run:
          name: Remove dev dependencies from api
          command: cd api &&  npm install --only=production
      - run:
          name: Create app archive
          command: |
            tar -czf archive.tar.gz ./package.json ./node_modules ./public
          working_directory: ~/project/app
      - store_artifacts:
          path: app/archive.tar.gz
          destination: /home/circleci/project/app.tar.gz
      - run:
          name: Create api archive
          command: |
            tar -czf archive.tar.gz ./package.json ./node_modules ./dist
          working_directory: ~/project/api
      - store_artifacts:
          path: api/archive.tar.gz
          destination: /home/circleci/project/api.tar.gz
  app-sentry-release:
    docker:
      - image: getsentry/sentry-cli:1.40.0
        environment:
          SENTRY_ORG: cheattyio
          SENTRY_PROJECT: cheattyio-app
    steps:
      - attach_workspace:
          at: ~/project
      - run: sentry-cli releases new --project ${SENTRY_PROJECT} ${SENTRY_PROJECT}@${CIRCLE_SHA1}
      - run: sentry-cli releases files ${SENTRY_PROJECT}@${CIRCLE_SHA1} upload-sourcemaps app/public/build
      - run: sentry-cli releases finalize ${SENTRY_PROJECT}@${CIRCLE_SHA1}
  api-sentry-release:
    docker:
      - image: getsentry/sentry-cli:1.40.0
        environment:
          SENTRY_ORG: cheattyio
          SENTRY_PROJECT: cheattyio-api
    steps:
      - attach_workspace:
          at: ~/project
      - run: sentry-cli releases new --project ${SENTRY_PROJECT} ${SENTRY_PROJECT}@${CIRCLE_SHA1}
      - run: sentry-cli releases files ${SENTRY_PROJECT}@${CIRCLE_SHA1} upload-sourcemaps api/dist
      - run: sentry-cli releases finalize ${SENTRY_PROJECT}@${CIRCLE_SHA1}

workflows:
  version: 2
  build:
    jobs:
      - app-npm-install
      - api-npm-install
      - app-lint:
          requires:
            - app-npm-install
      - api-lint:
          requires:
            - api-npm-install
      - app-validate:
          requires:
            - app-npm-install
      - app-build:
          requires:
            - app-lint
            - app-validate
      - api-build:
          requires:
            - api-lint
      - build-archives:
          requires:
            - app-build
            - api-build
      - app-sentry-release:
          context: sentry
          requires:
            - build-archives
          filters:
            branches:
              only:
                - develop
                - main
      - api-sentry-release:
          context: sentry
          requires:
            - build-archives
          filters:
            branches:
              only:
                - develop
                - main
