version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:15.3.0
  sentry:
    docker:
      - image: getsentry/sentry-cli:1.40.0

commands:
  npm_install:
    parameters:
      cache_key:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}
            - npm-install-<< parameters.cache_key >>
          paths:
            - node_modules
      - run:
          command: npm install
      - save_cache:
          key: npm-install-<< parameters.cache_key >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  sentry-release:
    parameters:
      project_key:
        type: string
    steps:
      - attach_workspace:
          at: ~/project
      - run: sentry-cli releases new --project << parameters.project_key >> << parameters.project_key >>@${CIRCLE_SHA1}
      - run: sentry-cli releases files << parameters.project_key >>@${CIRCLE_SHA1} upload-sourcemaps app/public
      - run: sentry-cli releases finalize << parameters.project_key >>@${CIRCLE_SHA1}

jobs:
  app-npm-install:
    executor: node
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - npm_install:
          cache_key: app
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
  app-lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run linter
          command: cd app && npm run lint
  app-validate:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run validate
          command: cd app && npm run validate
  app-build:
    executor: node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: cd app && npm run build:prod
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/public
  build-archives:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Remove dev dependencies from app
          command: cd app &&  npm install --only=production
      - run:
          name: Create archive
          command: tar -czf archive.tar.gz app/package.json app/node_modules app/public
      - store_artifacts:
          path: archive.tar.gz
          destination: /home/circleci/project/archive.tar.gz
  app-sentry-release:
    executor: sentry
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - sentry-release:
          project_key: cheattyio-app
workflows:
  version: 2
  build:
    jobs:
      - app-npm-install
      - app-lint:
          requires:
            - app-npm-install
      - app-validate:
          requires:
            - app-npm-install
      - app-build:
          requires:
            - app-lint
            - app-validate
      - build-archives:
          requires:
            - app-build
      - app-sentry-release:
          context: sentry
          requires:
            - build-archives
