server:
  port: 3002
  production: false
  origin: 'http://localhost:5000'

sentry:
  url: 'https://...@....ingest.sentry.io/...'
  traces: 1.0

db:
  type: 'mongodb'
  host: 'localhost'
  port: 27017
  database: 'cheatty'
  username: 'username'
  password: 'root'
