---
- hosts: main_compute
  vars_files:
    - vars/circleci.yaml
    - vars/github.yaml
  tasks:
    - deploy_helper:
        path: "{{ item }}"
        keep_releases: 3
      tags:
        - always
      with_items:
        - "{{ cheatty.api.folder }}"

    - import_role:
        name: build
      tags:
        - always
      vars:
        repository_name: dimitrilahaye/cheatty
        job_name: build-archives

    - import_role:
        name: deploy
      tags:
        - api
      environment: "{{ cheatty.api.node_env }}"
      vars:
        path: "{{ cheatty.api.folder }}"
        artifact: api.tar.gz
        after_finalize:
          - systemctl restart cheatty-api
