---
- hosts: cheatty
  tags:
    - api
  vars_files:
    - vars/circleci.yaml
    - vars/github.yaml
  tasks:
    - deploy_helper:
        path: "{{ cheatty.api.folder }}"
        keep_releases: 3
      tags:
        - always

    - import_role:
        name: build
      tags:
        - always
      vars:
        repository_name: dimitrilahaye/cheatty
        job_name: build-archives

    - import_role:
        name: deploy
      environment: "{{ cheatty.api.node_env }}"
      vars:
        path: "{{ cheatty.api.folder }}"
        artifact: api.tar.gz
        after_finalize:
          - systemctl restart cheatty-api

- hosts: cheatty
  tags:
    - app
  vars_files:
    - vars/circleci.yaml
    - vars/github.yaml
  tasks:
    - deploy_helper:
        path: "{{ cheatty.app.folder }}"
        keep_releases: 3
      tags:
        - always

    - import_role:
        name: build
      tags:
        - always
      vars:
        repository_name: dimitrilahaye/cheatty
        job_name: build-archives

    - import_role:
        name: deploy
      environment: "{{ cheatty.app.node_env }}"
      tags:
        - app
      vars:
        path: "{{ cheatty.app.folder }}"
        artifact: app.tar.gz
        after_finalize:
          - systemctl restart cheatty-app
