---
- hosts: cheatty
  tasks:
    - name: Create cheatty api group
      group:
        name: cheatty-api
        state: present
    - name: Create cheatty api user
      user:
        name: cheatty-api
        group: cheatty-api
        state: present

    - name: Create cheatty app group
      group:
        name: cheatty-app
        state: present
    - name: Create cheatty app user
      user:
        name: cheatty-app
        group: cheatty-app
        state: present

    - name: Create the required folders
      tags:
        - always
      file:
        path: "{{ item }}"
        state: directory
        owner: cheatty
        group: cheatty
        mode: 0755
      loop:
        - "{{ cheatty.folder }}"
        - "{{ cheatty.api.folder }}"
        - "{{ cheatty.app.folder }}"

    - name: Setup cheatty-api service
      import_role:
        name: service
      vars:
        service: cheatty-api
        description: Cheatty API server
        user: cheatty
        group: cheatty
        working_directory: "{{ cheatty.api.folder }}/current"
        command: /usr/bin/node dist/main
        env: "{{ cheatty.api.node_env }}"

    - name: Setup cheatty-app service
      import_role:
        name: service
      vars:
        service: cheatty-app
        description: Cheatty APP server
        user: cheatty
        group: cheatty
        working_directory: "{{ cheatty.app.folder }}/current"
        command: "{{ cheatty.app.folder }}/current/node_modules/rollup/dist/bin/rollup -c -w"
        env: "{{ cheatty.app.node_env }}"

    - name: Setup cheatty site
      import_role:
        name: site
      vars:
        email: "{{ contact }}"
        site: cheatty
        basic_auth_user: "{{ cheatty.app.basic_auth_user }}"
        basic_auth_password: "{{ cheatty.app.basic_auth_password }}"
        domain: "{{ cheatty.hostname }}"
        config: |
          root {{ cheatty.app.folder }}/current/public;

          location / {
              try_files $uri /index.html;
              add_header cache-control "no-store";
          }

          location /api/ {
            proxy_pass http://localhost:{{ cheatty.api.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }
